# Generated by Django 5.0.6 on 2024-07-02 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sing', '0004_alter_song_singer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='singer',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='singer',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='song',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='song',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='singer',
            name='name',
            field=models.TextField(default='Unknown', max_length=20),
        ),
    ]
