# Generated by Django 5.0.6 on 2024-07-04 16:07

import sing.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sing', '0006_tag_singer_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='singer',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=sing.models.image_upload_path),
        ),
    ]
