# Generated by Django 5.0.6 on 2024-07-04 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sing', '0008_remove_singer_image_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Image',
            new_name='SingerImage',
        ),
    ]
