# Generated by Django 5.0.6 on 2024-07-05 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sing', '0009_rename_image_singerimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='singerimage',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='singerimage',
            name='singer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image', to='sing.singer'),
        ),
    ]
