# Generated by Django 5.0.6 on 2024-07-05 15:22

import sing.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sing', '0010_alter_singerimage_id_alter_singerimage_singer'),
    ]

    operations = [
        migrations.AddField(
            model_name='singer',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=sing.models.image_upload_path),
        ),
        migrations.DeleteModel(
            name='SingerImage',
        ),
    ]
