# Generated by Django 5.0.6 on 2024-07-05 15:31

import django.db.models.deletion
import sing.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sing', '0011_singer_image_delete_singerimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='singer',
            name='image',
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to=sing.models.image_upload_path)),
                ('singer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='sing.singer')),
            ],
        ),
    ]
